### ISSUE TITLE
About the performance without multi-cropping?

### ISSUE THREAD

**Issue by zhanyuanyang** [Frankluox/FewShotPL#4]
Hi, thanks for your nice work.

Since the results reported in the paper are based on multi-cropping, I would like to know if there are raw results that do not use multi-cropping at evaluation?

**Comment by Frankluox** [comment]
Hi, since every position of the spatial feature obtained from ResNet has a receptive field covering the whole image,  it is expected that every position in the feature would be influenced by image background, which is undesirable if we wish to use the raw spatial feature (before global pooling) as the indicator to remove the background effect. In practice, the performance drops severely without multi-cropping (I've tried, the performance is worse than vallina approaches). So necessarily, we instead remove some parts of images from the beginning of image processing, i.e., using crops of images as candidates.

**Comment by zhanyuanyang** [comment]
I see, thanks for your reply.
